### PR TITLE
PullMergeReqREADME.md

### LINKED ISSUE #1: Redesign the readme file
The Readme file is often the first file that the users read. It is a text file that contains information for the user about the software, project, code, or game, or it might contain instructions, help, or details about the patches or updates.

Try creating a good readme file that catches the eye of readers with the main points bold and clear to read.
Additionally documentation of libraries and technologies used could be added for ease of access.

### PR DESCRIPTION
**Pull request by DanielZhang111**
I have no clue if this is enough, I tried to add as much as I thought was needed. Pls tell me if you want anything changed as I really need the pull/merge request lol :)

### CODE REVIEW

**Comment by sadnyd** [comment]
I am merging the pr for now. If you can put the common car brand section below the common car types and add some pictures for each of the car types, that would help. Nice work.

**Comment by DanielZhang111** [comment]
So it was accepted? or not?

**Comment by DanielZhang111** [comment]
Why does it say "not participating?"

**Comment by DanielZhang111** [comment]
Can you accept it? Cause it counts for hacktoberfest right?

**Comment by DanielZhang111** [comment]
Can I get the hacktoberfest-accepted label counted for hacktoberfest?

**Comment by sadnyd** [comment]
It will show up in your hacktoberfest page in 5-30 mins.

**Comment by DanielZhang111** [comment]
It shows up, but it says Not Participating. That means its done but doesnt count for Hacktoberfest? Maybe not, I'll check again tomorrow. Thanks tho!

**Comment by DanielZhang111** [comment]
Ok Nevermind its on the "Waiting" Now. Thanks!

**Comment by DanielZhang111** [comment]
If I manage to finish all 4 pull/merge requests before Hacktoberfest ends, then I will be back and finish whats leftover! I currently have 1 accepted and 1 waiting (which is this one). Thanks!

**Pull request merged**
